import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generatePDF(result, inputRecord) {
  const doc = new jsPDF();
  const now = new Date().toLocaleString('en-IN');
  const reportId = `CG-${Date.now()}`;

  // PAGE 1: Header
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, 210, 297, 'F');

  doc.setTextColor(249, 250, 251);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('ClinicalGuard', 20, 30);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(156, 163, 175);
  doc.text('Clinical Trial Data Integrity Report', 20, 40);

  // Report metadata
  doc.setFontSize(10);
  doc.setTextColor(209, 213, 219);
  doc.text(`Report ID: ${reportId}`, 20, 58);
  doc.text(`Generated: ${now}`, 20, 66);
  doc.text(`Trial ID: ${inputRecord.trial_id || 'N/A'}`, 20, 74);
  doc.text(`Site ID: ${inputRecord.site_id || 'N/A'}`, 20, 82);

  // Verdict banner
  const isAuth = result.decision === 'AUTHENTIC';
  doc.setFillColor(isAuth ? 20 : 239, isAuth ? 184 : 68, isAuth ? 166 : 68, 0.2);
  doc.roundedRect(20, 95, 170, 28, 4, 4, 'F');
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isAuth ? 94 : 248, isAuth ? 234 : 113, isAuth ? 212 : 113);
  doc.text(result.decision, 105, 113, { align: 'center' });

  // PAGE 2: Feature table
  doc.addPage();
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, 210, 297, 'F');
  doc.setTextColor(249, 250, 251);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Record — 13 Features', 20, 24);

  const featureRows = [
    ['Age', inputRecord.age, '18–80'],
    ['BP Systolic', inputRecord.bp_systolic, '90–139 mmHg'],
    ['BP Diastolic', inputRecord.bp_diastolic, '60–89 mmHg'],
    ['Glucose', inputRecord.glucose, '70–125 mg/dL'],
    ['Heart Rate', inputRecord.hr, '60–100 bpm'],
    ['SpO2', inputRecord.spo2, '95–100%'],
    ['Diagnosis Encoded', inputRecord.diagnosis_encoded, '0–4'],
    ['Previous Trials', inputRecord.previous_trials, '0–10'],
    ['Product Experience', inputRecord.product_experience, '0–5'],
    ['Last Trial Outcome', inputRecord.last_trial_outcome, '0/1'],
    ['Health Risk Score', inputRecord.health_risk_score, '0.00–1.00'],
    ['Age Group Adult', inputRecord.age_grp_adult, '0/1'],
    ['Age Group Elderly', inputRecord.age_grp_elderly, '0/1'],
  ];

  doc.autoTable({
    startY: 32,
    head: [['Feature', 'Value', 'Normal Range']],
    body: featureRows,
    theme: 'grid',
    styles: {
      fillColor: [26, 31, 46],
      textColor: [209, 213, 219],
      fontSize: 10,
      cellPadding: 5,
    },
    headStyles: {
      fillColor: [31, 41, 55],
      textColor: [249, 250, 251],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [31, 41, 55] },
  });

  // PAGE 3: ML Result
  doc.addPage();
  doc.setFillColor(15, 17, 23);
  doc.rect(0, 0, 210, 297, 'F');
  doc.setTextColor(249, 250, 251);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('ML Verdict & Blockchain', 20, 24);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(209, 213, 219);
  doc.text(`Decision:             ${result.decision}`, 20, 42);
  doc.text(`Risk Level:           ${result.risk_level}`, 20, 52);
  doc.text(`Confidence Authentic: ${result.confidence_authentic?.toFixed(2)}%`, 20, 62);
  doc.text(`Confidence Manip:     ${result.confidence_manipulated?.toFixed(2)}%`, 20, 72);
  doc.text(`Blockchain Action:    ${result.blockchain_action}`, 20, 82);
  doc.text(`SFO Override:         ${result.sfo_override ? 'YES' : 'NO'}`, 20, 92);

  doc.setTextColor(156, 163, 175);
  doc.setFontSize(9);
  doc.text('SHA-256 Data Hash:', 20, 110);
  doc.setFont('courier', 'normal');
  doc.setTextColor(94, 234, 212);
  doc.text(result.data_hash || 'N/A', 20, 118);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(156, 163, 175);
  doc.text('Blockchain TX:', 20, 132);
  doc.setFont('courier', 'normal');
  doc.setTextColor(209, 213, 219);
  doc.text(result.tx_hash || 'N/A', 20, 140);

  // PAGE 4: Gemini Reasoning
  if (result.gemini_reasoning) {
    doc.addPage();
    doc.setFillColor(15, 17, 23);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(249, 250, 251);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('AI Clinical Reasoning', 20, 24);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(209, 213, 219);
    const lines = doc.splitTextToSize(result.gemini_reasoning, 170);
    doc.text(lines, 20, 38);

    doc.setTextColor(139, 92, 246);
    doc.setFontSize(9);
    doc.text('Generated by Gemini 2.5 Flash — ClinicalGuard V2.0', 20, 280);
  }

  doc.save(`ClinicalGuard_Report_${reportId}.pdf`);
}
